### ISSUE TITLE
Combine lead and deputy into one thing

### ISSUE THREAD

**Issue by eteq** [astropy/coordination#145]
*Description from @astrofrog:*

The idea of combining lead and deputy into one category is to avoid confusion about the different 'kinds' of deputies and which ones get write access or not. The suggested path forward is to merge lead and deputy into a single 'maintainer' category, and to give write access to all. People would would previously have been considered in training would then become mentees under the planned mentorship program, and would be listed/recognized elsewhere but not in the overall roles page.

**Comment by kelle** [comment]
resolved at Coordination meeting. new issue opened in website repo.
